version: "3"
services:
  nearest-toilet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./controllers:/app/controllers
      - ./routing:/app/routing
      - ./service:/app/service
    command: go run main.go

  nearest-toilet-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - nearest-toilet-backend
